import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — How Very Dare You",
  description:
    "Terms of service for How Very Dare You. Understand the terms governing your use of our AI content advisory platform.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-8 py-4">
      <div>
        <h1 className="text-3xl font-extrabold tracking-tight">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: March 3, 2026
        </p>
      </div>

      <section className="space-y-3">
        <h2 className="text-xl font-bold tracking-tight">
          Acceptance of Terms
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          By accessing or using How Very Dare You (&quot;the Service&quot;),
          you agree to be bound by these Terms of Service. If you do not agree
          to these terms, do not use the Service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold tracking-tight">
          AI-Generated Content Disclaimer
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          All content advisories, ratings, and analysis on this platform are
          generated by artificial intelligence. While we strive for accuracy
          and consistency, AI-generated ratings should be used as a guide, not
          a definitive assessment of content suitability. We recommend parents
          use our ratings alongside their own judgment and, where possible,
          preview content before allowing children to watch.
        </p>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Ratings reflect analysis of available subtitle transcripts and
          metadata. Content that relies heavily on visual themes, subtext, or
          cultural context not present in dialogue may not be fully captured.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold tracking-tight">
          Description of Service
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          How Very Dare You provides AI-powered content advisories for movies
          and TV shows. The Service includes:
        </p>
        <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
          <li>Browsing and searching analyzed titles (free, no account required)</li>
          <li>Requesting on-demand AI analyses (free account: 3/day, Premium: 10/day)</li>
          <li>Personalized category weighting and watchlist (Premium subscription)</li>
          <li>Submitting rating corrections (free account required)</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold tracking-tight">
          Subscription Terms
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Premium subscriptions are billed monthly at the current rate
          ($4.99/month) through Stripe. You may cancel at any time through
          your Settings page. Cancellation takes effect at the end of the
          current billing period. We do not offer refunds for partial billing
          periods.
        </p>
        <p className="text-sm leading-relaxed text-muted-foreground">
          We reserve the right to change subscription pricing with 30 days
          notice to existing subscribers.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold tracking-tight">Acceptable Use</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          You agree not to:
        </p>
        <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
          <li>Scrape, crawl, or bulk-download rating data without permission</li>
          <li>Submit fraudulent or malicious corrections</li>
          <li>Attempt to manipulate ratings or abuse on-demand analysis limits</li>
          <li>Use the Service for any unlawful purpose</li>
          <li>Interfere with or disrupt the Service infrastructure</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold tracking-tight">
          Intellectual Property
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Movie and TV show metadata, poster images, and streaming provider
          information are sourced from TMDB (The Movie Database) and used
          under their API terms of use. TMDB is not affiliated with How Very
          Dare You.
        </p>
        <p className="text-sm leading-relaxed text-muted-foreground">
          AI-generated ratings, notes, and composite scores are original
          content created by How Very Dare You and may not be reproduced
          without attribution.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold tracking-tight">
          Limitation of Liability
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          The Service is provided &quot;as is&quot; without warranties of any
          kind. We are not liable for any damages arising from your use of the
          Service, including but not limited to: reliance on AI-generated
          ratings, viewing decisions made based on our advisories, or service
          interruptions.
        </p>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Our total liability to you for any claim arising from the Service
          shall not exceed the amount you paid us in the 12 months preceding
          the claim.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold tracking-tight">
          Affiliate Disclosure
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Some streaming links on our platform may contain affiliate links. We
          may earn a small commission at no extra cost to you when you click
          through and subscribe to a streaming service. Affiliate
          relationships do not influence our AI-generated ratings.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold tracking-tight">Changes to Terms</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          We may update these terms from time to time. Continued use of the
          Service after changes are posted constitutes acceptance of the
          revised terms. Material changes will be communicated via email to
          registered users.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-bold tracking-tight">Contact</h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          Questions about these terms? Contact us at legal@howverydareyou.com.
        </p>
      </section>
    </div>
  );
}
